### ISSUE TITLE
Why it doesn't work for me

### ISSUE THREAD

**Issue by BobAnkh** [subhamX/github#2]
I am facing problem of using your github actions. I configure the AutoPR.yml according to your instructions but it seems not working.

Here is the configuration file:

```
name: Add Recently Created Pull Requests to Project Column
on:
  schedule:
    - cron: "0/5 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Handle Linux Command
      uses: subhamX/github-project-bot@v1.0.0
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        COLUMN_NAME: In progress
        PROJECT_URL: https://github.com/BobAnkh/LinuxBeginner/projects/1
        # For User Owned Project -> PROJECT_URL: https://github.com/users/UNAME/projects/1
        REPO_URL: https://github.com/BobAnkh/LinuxBeginner
        # For User Owned Repo -> REPO_URL: https://github.com/UNAME/repo1
    - name: Handle Linux Tool
      uses: subhamX/github-project-bot@v1.0.0
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        COLUMN_NAME: In progress
        PROJECT_URL: https://github.com/BobAnkh/LinuxBeginner/projects/2
        # For User Owned Project -> PROJECT_URL: https://github.com/users/subhamX/projects/1
        REPO_URL: https://github.com/BobAnkh/LinuxBeginner
        # For User Owned Repo -> REPO_URL: https://github.com/UNAME/repo2
```

And here is the log of Github Actions titled ` Handle Linux Command`

> Run subhamX/github-project-bot@v1.0.0
(node:2469) UnhandledPromiseRejectionWarning: TypeError: (s || "").replace is not a function
    at escapeData (/home/runner/work/_actions/subhamX/github-project-bot/v1.0.0/dist/index.js:253:10)
    at Command.toString (/home/runner/work/_actions/subhamX/github-project-bot/v1.0.0/dist/index.js:247:35)
    at issueCommand (/home/runner/work/_actions/subhamX/github-project-bot/v1.0.0/dist/index.js:210:30)
    at Object.issue (/home/runner/work/_actions/subhamX/github-project-bot/v1.0.0/dist/index.js:214:5)
    at Object.error (/home/runner/work/_actions/subhamX/github-project-bot/v1.0.0/dist/index.js:647:15)
    at /home/runner/work/_actions/subhamX/github-project-bot/v1.0.0/dist/index.js:166:26
    at step (/home/runner/work/_actions/subhamX/github-project-bot/v1.0.0/dist/index.js:104:23)
    at Object.next (/home/runner/work/_actions/subhamX/github-project-bot/v1.0.0/dist/index.js:85:53)
    at /home/runner/work/_actions/subhamX/github-project-bot/v1.0.0/dist/index.js:79:71
    at new Promise (<anonymous>)
(node:2469) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2469) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

So is there something more I have to configure or is there something I configure it wrong? Please help me! Thank you for  your time!
